[package]
name = "read_cam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nokhwa = {path="../nokhwa/", features=["input-native", "output-threaded"]}
image = "*"
